#!/usr/bin/env python3
"""Build the Amargi Carriage Series A deck PDFs in all four site languages.

Reads pitch-deck-src.html (English), applies the translation table for each
language, and prints each variant to PDF with headless Chrome:

    assets/pitch-deck-en.pdf   (also copied to assets/pitch-deck.pdf)
    assets/pitch-deck-zh.pdf
    assets/pitch-deck-th.pdf
    assets/pitch-deck-fil.pdf

Run from the repo root or the assets dir:  python3 assets/build-decks.py
Translation keys are exact strings from pitch-deck-src.html; if you edit the
deck copy, update the matching keys here (the script fails loudly on a miss).
"""
import os, shutil, subprocess, sys

CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "pitch-deck-src.html")

# Per-language CSS adjustments: CJK/Thai fall back to system fonts and need
# neutral letter-spacing / taller line-height for diacritics.
EXTRA_CSS = {
    "zh": 'body { font-family: "Satoshi", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif; }\n'
          "h1, h2 { letter-spacing: 0; }\n"
          ".eyebrow, .stat .label, .foot, .fly-node { letter-spacing: 0.08em; }",
    "th": 'body { font-family: "Satoshi", "Thonburi", "Noto Sans Thai", sans-serif; }\n'
          "h1, h2 { letter-spacing: 0; }\n"
          "h1 { line-height: 1.3; } h2 { line-height: 1.28; }\n"
          ".eyebrow, .stat .label, .foot, .fly-node { letter-spacing: 0.06em; }",
    "fil": "",
    "en": "",
}

ZH = [
    ("Powering green.<br>Every kilometre, electrified.", "绿色动力。<br>每一公里，皆为电动。"),
    ("Southeast Asia's integrated commercial EV ecosystem: vehicles, spare parts, and solar-powered charging under one roof.",
     "东南亚一体化商用电动车生态系统：车辆、零部件与太阳能充电，一站式服务。"),
    ("Series A · 2026", "A轮融资 · 2026"),
    ("Series A · Confidential", "A轮融资 · 机密"),
    ("01 · Who we are", "01 · 关于我们"),
    ("Twelve years in commercial transport.<br>Now fully electric.", "深耕商用运输十二年。<br>如今全面电动化。"),
    ("Transcool founded", "Transcool 成立"),
    ("Specialists in commercial air-conditioning systems for large vehicles, serving Singapore's biggest operators.",
     "专注大型车辆商用空调系统，服务新加坡最大的运输企业。"),
    ("The electric pivot", "转向电动化"),
    ("Evolved into integrated EV solutions as fleet electrification demand accelerated across the region.",
     "随着区域车队电动化需求加速，转型为一体化电动车解决方案。"),
    ("A dedicated integrated EV reseller and provider: vehicles, parts, and charging as one ecosystem.",
     "专业的一体化电动车经销与服务商：车辆、零部件与充电共成一体。"),
    ("Long-standing corporate clients including SMRT and ComfortDelGro", "长期企业客户包括 SMRT 与康福德高"),
    ("Operations extended into Thailand and Malaysia", "业务拓展至泰国与马来西亚"),
    ("First integrated EV solution pilot deployed in Thailand", "首个一体化电动车方案试点已在泰国落地"),
    ("02 · The market", "02 · 市场概览"),
    ("The commercial EV tipping point", "商用电动车的临界点"),
    ("Global commercial EV market by 2026, entering hyper-growth", "2026年全球商用电动车市场规模，进入高速增长期"),
    ("Light commercial EV demand: 1.14M units today to 16M+ by 2035", "轻型商用电动车需求：从目前114万辆增至2035年逾1,600万辆"),
    ("Our focus: Southeast Asia, where OEM production meets infrastructure buildout", "我们聚焦东南亚：整车产能与基础设施建设的交汇之地"),
    ("03 · The problem", "03 · 行业痛点"),
    ("Standard EVs fail modern fleets", "标准电动车难以满足现代车队"),
    ("Cost and supply barriers", "成本与供应壁垒"),
    ("Operators need large electric buses and taxis but face high upfront costs and unreliable supply chains.",
     "运营商需要大型电动巴士与出租车，却面临高昂前期成本与不稳定的供应链。"),
    ("Fragmented spare parts", "零部件供应碎片化"),
    ("Critical EV components take weeks to arrive, and every idle day is lost revenue for an operator.",
     "关键零部件需数周才能到货，每一天停运都是运营商的损失。"),
    ("Charging infrastructure gaps", "充电基础设施缺口"),
    ("Grid strain, slow deployment, and high operating costs make depot charging painful to run.",
     "电网压力、部署缓慢、运营成本高，令车场充电难以为继。"),
    ("Policy urgency, messy execution", "政策紧迫，执行混乱"),
    ("Singapore's 2040 EV vision and 2030 bus electrification targets, with regional mandates following, create demand faster than operators can execute.",
     "新加坡2040年电动化愿景与2030年巴士电动化目标，加上区域政策跟进，需求增长快于运营商的执行能力。"),
    ("04 · Our solution", "04 · 解决方案"),
    ("The resell · charge · parts flywheel", "销售 · 充电 · 零部件飞轮"),
    ('transform: translate(-50%,-50%);">Resell</div>', 'transform: translate(-50%,-50%);">销售</div>'),
    ('transform: translate(-50%,-50%);">Charge</div>', 'transform: translate(-50%,-50%);">充电</div>'),
    ('transform: translate(-50%,-50%);">Parts</div>', 'transform: translate(-50%,-50%);">零部件</div>'),
    ("One<br>ecosystem", "一体<br>生态"),
    ('margin-bottom: 12px;">Resell <span style="color: var(--accent-alt); font-size: 26px;">/ commercial EV sales</span>',
     'margin-bottom: 12px;">销售 <span style="color: var(--accent-alt); font-size: 26px;">/ 商用电动车销售</span>'),
    ("Large electric buses and e-taxis through proven OEM partnerships, an asset-light reseller model.",
     "通过成熟的整车厂合作销售大型电动巴士与电动出租车，轻资产经销模式。"),
    ('margin-bottom: 12px;">Charge <span style="color: var(--accent-alt); font-size: 26px;">/ solar charging hubs</span>',
     'margin-bottom: 12px;">充电 <span style="color: var(--accent-alt); font-size: 26px;">/ 太阳能充电枢纽</span>'),
    ("On-site solar generation, battery storage, and fast DC charging built for fleet schedules.",
     "光伏发电、储能电池与直流快充，围绕车队班次设计。"),
    ('margin-bottom: 12px;">Parts <span style="color: var(--accent-alt); font-size: 26px;">/ spare parts wholesale</span>',
     'margin-bottom: 12px;">零部件 <span style="color: var(--accent-alt); font-size: 26px;">/ 零部件批发</span>'),
    ("Regional inventory hub for batteries, motors, AC/DC components, tyres, and brake parts.",
     "区域库存中心：电池、电机、交直流部件、轮胎与制动件。"),
    ("Vehicles → parts → renewable charging. Each arm feeds the next.", "车辆 → 零部件 → 绿色充电。环环相扣，相互驱动。"),
    ("05 · Market opportunity", "05 · 市场机遇"),
    ("A S$680M beachhead, a regional runway", "6.8亿新元滩头市场，区域化增长跑道"),
    ("Singapore buses mandated 100% electric by 2040; only 240 electric today", "新加坡巴士须于2040年全面电动化；目前仅240辆为电动"),
    ("Singapore taxis electrifying: 2,500 electric today across Strides, ComfortDelGro, SMRT",
     "新加坡出租车加速电动化：Strides、康福德高与SMRT旗下已有2,500辆电动车"),
    ("Five-year addressable market: vehicles, parts, and charging", "五年可达市场：车辆、零部件与充电"),
    ("Projected EV component and commercial vehicle market by 2035", "预计2035年电动车零部件与商用车市场规模"),
    ("Regional expansion runway", "区域扩张路径"),
    ("Malaysia · Thailand · Indonesia · Philippines", "马来西亚 · 泰国 · 印度尼西亚 · 菲律宾"),
    ("06 · Business model", "06 · 商业模式"),
    ("Four streams, one blended margin", "四大收入来源，一个综合毛利"),
    ("<th>Revenue stream</th>", "<th>收入来源</th>"),
    ("<th>Description</th>", "<th>说明</th>"),
    ("<th>Gross margin</th>", "<th>毛利率</th>"),
    ("<td>Vehicle resale</td>", "<td>整车销售</td>"),
    ("15-18% commission / markup on bus and e-taxi sales", "巴士与电动出租车销售的15-18%佣金或加价"),
    ("<td>Parts wholesale</td>", "<td>零部件批发</td>"),
    ("B2B bulk spare parts with high repeat order rates", "B2B批量零部件，复购率高"),
    ("<td>Charging hubs</td>", "<td>充电枢纽</td>"),
    ("Pay-per-use charging plus fleet subscriptions", "按次充电收费与车队订阅"),
    ("<td>Solar energy sales</td>", "<td>太阳能售电</td>"),
    ("Excess solar sold to grid, offsetting charging costs", "多余光伏电力售予电网，抵消充电成本"),
    ("Blended gross margin target", "综合毛利率目标"),
    ("07 · Recurring revenue", "07 · 经常性收入"),
    ("Charge &amp; Save", "充电即省钱"),
    ("Fleet operators pay a monthly subscription for access to our solar-storage charging hubs",
     "车队运营商按月订阅，使用我们的光储充电枢纽"),
    ("We charge S$0.25/kWh against a S$0.35 grid rate: the client saves, we keep the margin plus renewable energy certificates",
     "我们的电价为每度0.25新元，电网价为0.35新元：客户省钱，我们赚取差价并获得绿电证书"),
    ("Solar and storage integration lowers charging cost by 35% versus grid-only", "光伏加储能，较纯电网充电成本降低35%"),
    ("Hubs anchor loyalty: charging customers buy vehicles and parts from the same ecosystem",
     "枢纽绑定忠诚度：充电客户在同一生态内购买车辆与零部件"),
    ("Our rate per kWh", "我们的每度电价"),
    ("Grid rate per kWh", "电网每度电价"),
    ("Charging cost vs grid-only", "较纯电网充电成本"),
    ("08 · Why we win", "08 · 制胜之道"),
    ("Six layers of moat", "六重护城河"),
    ("Licensed &amp; compliant", "持牌合规"),
    ("Fully licensed under Singapore's strict EV import and charging regulations.", "全面符合新加坡严格的电动车进口与充电法规。"),
    ("Solar + storage edge", "光储优势"),
    ("35% cheaper charging than grid-only competitors, with RE certificate upside.", "较纯电网竞争者充电成本低35%，另有绿电证书收益。"),
    ("Deep parts inventory", "深度零部件库存"),
    ("Inverters, charging interfaces, and EV sensors in stock for minimal downtime versus new entrants, plus lifetime service contracts.",
     "逆变器、充电接口与传感器常备现货，停运时间远低于新进入者，并提供终身服务合约。"),
    ("First mover", "先发优势"),
    ("The first integrated hub ecosystem for commercial fleets in the region.", "区域内首个面向商用车队的一体化枢纽生态。"),
    ("12-year relationships", "十二年行业关系"),
    ("Established sales relationships with LTA, bus depots, and taxi companies.", "与陆交局、巴士车场及出租车公司建立了稳固的销售关系。"),
    ("Real unit economics", "扎实的单位经济"),
    ("S$70k-400k resale margin per BYD bus/truck and Wuling/Linxys van; S$10-15k per e-taxi.",
     "比亚迪巴士/卡车及五菱/Linxys厢式车每辆转售利润7万至40万新元；电动出租车每辆1万至1.5万新元。"),
    ("09 · Series A structure", "09 · A轮融资结构"),
    ("Convertible bonds, by design", "可转换债券，精心设计"),
    ("Investment protection", "投资保障"),
    ("Bond structure ranks ahead of equity, so capital is protected while the business scales.",
     "债券结构优先于股权，业务扩张期间资本受到保护。"),
    ("Conversion incentives", "转股激励"),
    ("Convert into equity at preferential terms as milestones are hit: upside without re-negotiation.",
     "达成里程碑后可按优惠条款转为股权：无需重新谈判即享上行收益。"),
    ("Yield potential", "收益潜力"),
    ("Coupon income from day one, with equity upside preserved.", "自首日起获得票息收入，同时保留股权上行空间。"),
    ("The structure in one line", "一句话概括"),
    ("Secured assets against an upscaling revenue stream", "以有担保资产对应持续放大的收入流"),
    ("10 · Use of funds", "10 · 资金用途"),
    ("S$9.9M, deployed for scale", "990万新元，为规模化布局"),
    ("Vehicle inventory: pre-order buses &amp; taxis at bulk discount", "整车库存：以批量折扣预订巴士与出租车"),
    ("Three solar charging hubs: east, north, west", "三座太阳能充电枢纽：东部、北部、西部"),
    ("Spare parts warehousing &amp; logistics", "零部件仓储与物流"),
    ("AI fleet platform: charging bookings, parts ordering", "AI车队平台：充电预约与零部件下单"),
    ("Team &amp; sales: fleet sales, operations, engineering", "团队与销售：车队销售、运营与工程"),
    ("11 · Roadmap", "11 · 发展路线"),
    ("Scaling to 50,000 vehicles", "迈向五万辆规模"),
    ("Series A &amp; hubs", "A轮与充电枢纽"),
    ("Close the round, secure vehicle inventory, energise the first solar charging hubs.",
     "完成融资，锁定整车库存，首批光储充电枢纽投运。"),
    ("Scale inventory", "扩大库存"),
    ("Expand parts warehousing and vehicle stock; deepen operator subscriptions.",
     "扩充零部件仓储与整车库存，深化运营商订阅。"),
    ("50,000+ vehicles", "五万辆以上"),
    ("Regional scale across Southeast Asia, with the flywheel compounding across markets.",
     "飞轮效应跨市场叠加，实现东南亚区域化规模。"),
    ("Exit paths", "退出路径"),
    ("Acquisition by a regional energy / mobility player · IPO on SGX Catalist or Nasdaq",
     "被区域能源或出行企业并购 · 在新交所凯利板或纳斯达克上市"),
    ("Join the quiet revolution.", "加入这场静谧革命。"),
]

TH = [
    ("Powering green.<br>Every kilometre, electrified.", "พลังงานสีเขียว<br>ทุกกิโลเมตร ขับเคลื่อนด้วยไฟฟ้า"),
    ("Southeast Asia's integrated commercial EV ecosystem: vehicles, spare parts, and solar-powered charging under one roof.",
     "ระบบนิเวศรถยนต์ไฟฟ้าเชิงพาณิชย์ครบวงจรของเอเชียตะวันออกเฉียงใต้: ยานพาหนะ อะไหล่ และการชาร์จพลังงานแสงอาทิตย์ ครบจบในที่เดียว"),
    ("Series A · 2026", "ซีรีส์ A · 2026"),
    ("Series A · Confidential", "ซีรีส์ A · เอกสารลับ"),
    ("01 · Who we are", "01 · เราคือใคร"),
    ("Twelve years in commercial transport.<br>Now fully electric.", "สิบสองปีในธุรกิจขนส่งเชิงพาณิชย์<br>วันนี้พร้อมเป็นไฟฟ้าเต็มรูปแบบ"),
    ("Transcool founded", "ก่อตั้ง Transcool"),
    ("Specialists in commercial air-conditioning systems for large vehicles, serving Singapore's biggest operators.",
     "ผู้เชี่ยวชาญระบบปรับอากาศเชิงพาณิชย์สำหรับยานพาหนะขนาดใหญ่ ให้บริการผู้ประกอบการรายใหญ่ที่สุดของสิงคโปร์"),
    ("The electric pivot", "จุดเปลี่ยนสู่ไฟฟ้า"),
    ("Evolved into integrated EV solutions as fleet electrification demand accelerated across the region.",
     "พัฒนาสู่โซลูชัน EV ครบวงจร เมื่อความต้องการเปลี่ยนฟลีตเป็นไฟฟ้าเร่งตัวทั่วภูมิภาค"),
    ("A dedicated integrated EV reseller and provider: vehicles, parts, and charging as one ecosystem.",
     "ผู้จำหน่ายและผู้ให้บริการ EV ครบวงจร: ยานพาหนะ อะไหล่ และการชาร์จ ในระบบนิเวศเดียว"),
    ("Long-standing corporate clients including SMRT and ComfortDelGro", "ลูกค้าองค์กรระยะยาว รวมถึง SMRT และ ComfortDelGro"),
    ("Operations extended into Thailand and Malaysia", "ขยายการดำเนินงานสู่ประเทศไทยและมาเลเซีย"),
    ("First integrated EV solution pilot deployed in Thailand", "นำร่องโซลูชัน EV ครบวงจรครั้งแรกในประเทศไทย"),
    ("02 · The market", "02 · ตลาด"),
    ("The commercial EV tipping point", "จุดพลิกผันของ EV เชิงพาณิชย์"),
    ("Global commercial EV market by 2026, entering hyper-growth", "ตลาด EV เชิงพาณิชย์ทั่วโลกภายในปี 2026 เข้าสู่ช่วงเติบโตก้าวกระโดด"),
    ("Light commercial EV demand: 1.14M units today to 16M+ by 2035",
     "ความต้องการรถ EV เชิงพาณิชย์ขนาดเล็ก: จาก 1.14 ล้านคันวันนี้ สู่กว่า 16 ล้านคันในปี 2035"),
    ("Our focus: Southeast Asia, where OEM production meets infrastructure buildout",
     "โฟกัสของเรา: เอเชียตะวันออกเฉียงใต้ จุดบรรจบของฐานผลิต OEM และโครงสร้างพื้นฐาน"),
    ("03 · The problem", "03 · ปัญหา"),
    ("Standard EVs fail modern fleets", "EV มาตรฐานไม่ตอบโจทย์ฟลีตยุคใหม่"),
    ("Cost and supply barriers", "อุปสรรคด้านต้นทุนและซัพพลาย"),
    ("Operators need large electric buses and taxis but face high upfront costs and unreliable supply chains.",
     "ผู้ประกอบการต้องการรถบัสและแท็กซี่ไฟฟ้าขนาดใหญ่ แต่เผชิญต้นทุนเริ่มต้นสูงและซัพพลายเชนที่ไม่แน่นอน"),
    ("Fragmented spare parts", "อะไหล่กระจัดกระจาย"),
    ("Critical EV components take weeks to arrive, and every idle day is lost revenue for an operator.",
     "ชิ้นส่วน EV สำคัญใช้เวลาหลายสัปดาห์กว่าจะมาถึง และทุกวันที่รถจอดคือรายได้ที่หายไป"),
    ("Charging infrastructure gaps", "ช่องว่างโครงสร้างพื้นฐานการชาร์จ"),
    ("Grid strain, slow deployment, and high operating costs make depot charging painful to run.",
     "ภาระโครงข่ายไฟฟ้า การติดตั้งล่าช้า และต้นทุนดำเนินงานสูง ทำให้การชาร์จในดีโปเป็นเรื่องยาก"),
    ("Policy urgency, messy execution", "นโยบายเร่งด่วน การลงมือยังสับสน"),
    ("Singapore's 2040 EV vision and 2030 bus electrification targets, with regional mandates following, create demand faster than operators can execute.",
     "วิสัยทัศน์ EV ปี 2040 และเป้ารถบัสไฟฟ้าปี 2030 ของสิงคโปร์ พร้อมนโยบายภูมิภาคที่ตามมา สร้างดีมานด์เร็วกว่าที่ผู้ประกอบการจะรับมือได้"),
    ("04 · Our solution", "04 · โซลูชันของเรา"),
    ("The resell · charge · parts flywheel", "ฟลายวีล ขาย · ชาร์จ · อะไหล่"),
    ('transform: translate(-50%,-50%);">Resell</div>', 'transform: translate(-50%,-50%);">ขาย</div>'),
    ('transform: translate(-50%,-50%);">Charge</div>', 'transform: translate(-50%,-50%);">ชาร์จ</div>'),
    ('transform: translate(-50%,-50%);">Parts</div>', 'transform: translate(-50%,-50%);">อะไหล่</div>'),
    ("One<br>ecosystem", "หนึ่ง<br>ระบบนิเวศ"),
    ('margin-bottom: 12px;">Resell <span style="color: var(--accent-alt); font-size: 26px;">/ commercial EV sales</span>',
     'margin-bottom: 12px;">ขาย <span style="color: var(--accent-alt); font-size: 26px;">/ จำหน่าย EV เชิงพาณิชย์</span>'),
    ("Large electric buses and e-taxis through proven OEM partnerships, an asset-light reseller model.",
     "รถบัสไฟฟ้าขนาดใหญ่และแท็กซี่ไฟฟ้า ผ่านพันธมิตร OEM ที่พิสูจน์แล้ว ในโมเดลตัวแทนจำหน่ายแบบ asset-light"),
    ('margin-bottom: 12px;">Charge <span style="color: var(--accent-alt); font-size: 26px;">/ solar charging hubs</span>',
     'margin-bottom: 12px;">ชาร์จ <span style="color: var(--accent-alt); font-size: 26px;">/ ฮับชาร์จพลังงานแสงอาทิตย์</span>'),
    ("On-site solar generation, battery storage, and fast DC charging built for fleet schedules.",
     "ผลิตไฟจากโซลาร์ในพื้นที่ แบตเตอรี่กักเก็บ และชาร์จเร็ว DC ออกแบบตามตารางฟลีต"),
    ('margin-bottom: 12px;">Parts <span style="color: var(--accent-alt); font-size: 26px;">/ spare parts wholesale</span>',
     'margin-bottom: 12px;">อะไหล่ <span style="color: var(--accent-alt); font-size: 26px;">/ ขายส่งอะไหล่</span>'),
    ("Regional inventory hub for batteries, motors, AC/DC components, tyres, and brake parts.",
     "ศูนย์สต็อกระดับภูมิภาค: แบตเตอรี่ มอเตอร์ ชิ้นส่วน AC/DC ยาง และระบบเบรก"),
    ("Vehicles → parts → renewable charging. Each arm feeds the next.",
     "ยานพาหนะ → อะไหล่ → การชาร์จพลังงานสะอาด แต่ละแขนขับเคลื่อนซึ่งกันและกัน"),
    ("05 · Market opportunity", "05 · โอกาสทางตลาด"),
    ("A S$680M beachhead, a regional runway", "ฐานตลาด 680 ล้านดอลลาร์สิงคโปร์ พร้อมรันเวย์สู่ภูมิภาค"),
    ("Singapore buses mandated 100% electric by 2040; only 240 electric today",
     "รถบัสสิงคโปร์ต้องเป็นไฟฟ้า 100% ภายในปี 2040; วันนี้มีเพียง 240 คัน"),
    ("Singapore taxis electrifying: 2,500 electric today across Strides, ComfortDelGro, SMRT",
     "แท็กซี่สิงคโปร์กำลังเปลี่ยนเป็นไฟฟ้า: 2,500 คันแล้วใน Strides, ComfortDelGro, SMRT"),
    ("Five-year addressable market: vehicles, parts, and charging", "ตลาดที่เข้าถึงได้ในห้าปี: ยานพาหนะ อะไหล่ และการชาร์จ"),
    ("Projected EV component and commercial vehicle market by 2035", "คาดการณ์ตลาดชิ้นส่วน EV และรถเชิงพาณิชย์ภายในปี 2035"),
    ("Regional expansion runway", "เส้นทางขยายสู่ภูมิภาค"),
    ("Malaysia · Thailand · Indonesia · Philippines", "มาเลเซีย · ไทย · อินโดนีเซีย · ฟิลิปปินส์"),
    ("06 · Business model", "06 · โมเดลธุรกิจ"),
    ("Four streams, one blended margin", "สี่กระแสรายได้ หนึ่งมาร์จิ้นรวม"),
    ("<th>Revenue stream</th>", "<th>กระแสรายได้</th>"),
    ("<th>Description</th>", "<th>รายละเอียด</th>"),
    ("<th>Gross margin</th>", "<th>อัตรากำไรขั้นต้น</th>"),
    ("<td>Vehicle resale</td>", "<td>ขายยานพาหนะ</td>"),
    ("15-18% commission / markup on bus and e-taxi sales", "ค่าคอมมิชชันหรือมาร์กอัป 15-18% จากการขายรถบัสและแท็กซี่ไฟฟ้า"),
    ("<td>Parts wholesale</td>", "<td>ขายส่งอะไหล่</td>"),
    ("B2B bulk spare parts with high repeat order rates", "อะไหล่ B2B แบบเหมาจำนวน อัตราสั่งซื้อซ้ำสูง"),
    ("<td>Charging hubs</td>", "<td>ฮับชาร์จ</td>"),
    ("Pay-per-use charging plus fleet subscriptions", "ค่าชาร์จตามการใช้งาน บวกค่าสมาชิกฟลีต"),
    ("<td>Solar energy sales</td>", "<td>ขายไฟโซลาร์</td>"),
    ("Excess solar sold to grid, offsetting charging costs", "ขายไฟส่วนเกินเข้ากริด ชดเชยต้นทุนการชาร์จ"),
    ("Blended gross margin target", "เป้าหมายอัตรากำไรขั้นต้นรวม"),
    ("07 · Recurring revenue", "07 · รายได้ประจำ"),
    ("Charge &amp; Save", "ชาร์จแล้วประหยัด"),
    ("Fleet operators pay a monthly subscription for access to our solar-storage charging hubs",
     "ผู้ประกอบการฟลีตจ่ายค่าสมาชิกรายเดือน เพื่อใช้ฮับชาร์จโซลาร์พร้อมแบตเตอรี่ของเรา"),
    ("We charge S$0.25/kWh against a S$0.35 grid rate: the client saves, we keep the margin plus renewable energy certificates",
     "เราคิดค่าไฟ 0.25 ดอลลาร์สิงคโปร์/kWh เทียบกริด 0.35: ลูกค้าประหยัด เราได้มาร์จิ้นพร้อมใบรับรองพลังงานหมุนเวียน"),
    ("Solar and storage integration lowers charging cost by 35% versus grid-only",
     "โซลาร์บวกระบบกักเก็บ ลดต้นทุนการชาร์จ 35% เทียบกับใช้กริดอย่างเดียว"),
    ("Hubs anchor loyalty: charging customers buy vehicles and parts from the same ecosystem",
     "ฮับสร้างความภักดี: ลูกค้าที่ชาร์จซื้อรถและอะไหล่จากระบบนิเวศเดียวกัน"),
    ("Our rate per kWh", "อัตราของเราต่อ kWh"),
    ("Grid rate per kWh", "อัตรากริดต่อ kWh"),
    ("Charging cost vs grid-only", "ต้นทุนชาร์จเทียบกริดอย่างเดียว"),
    ("08 · Why we win", "08 · เหตุผลที่เราชนะ"),
    ("Six layers of moat", "หกชั้นของคูเมืองธุรกิจ"),
    ("Licensed &amp; compliant", "มีใบอนุญาตถูกต้อง"),
    ("Fully licensed under Singapore's strict EV import and charging regulations.",
     "ได้รับอนุญาตครบถ้วนภายใต้กฎเข้มงวดด้านการนำเข้าและการชาร์จ EV ของสิงคโปร์"),
    ("Solar + storage edge", "ความได้เปรียบโซลาร์+กักเก็บ"),
    ("35% cheaper charging than grid-only competitors, with RE certificate upside.",
     "ค่าชาร์จถูกกว่าคู่แข่งที่ใช้กริดอย่างเดียว 35% พร้อมอัปไซด์จากใบรับรอง RE"),
    ("Deep parts inventory", "สต็อกอะไหล่เชิงลึก"),
    ("Inverters, charging interfaces, and EV sensors in stock for minimal downtime versus new entrants, plus lifetime service contracts.",
     "อินเวอร์เตอร์ หัวชาร์จ และเซ็นเซอร์ EV พร้อมส่ง ดาวน์ไทม์ต่ำกว่าผู้เล่นใหม่ พร้อมสัญญาบริการตลอดอายุ"),
    ("First mover", "ผู้บุกเบิก"),
    ("The first integrated hub ecosystem for commercial fleets in the region.",
     "ระบบนิเวศฮับครบวงจรแห่งแรกสำหรับฟลีตเชิงพาณิชย์ในภูมิภาค"),
    ("12-year relationships", "สายสัมพันธ์ 12 ปี"),
    ("Established sales relationships with LTA, bus depots, and taxi companies.",
     "ความสัมพันธ์การขายที่มั่นคงกับ LTA ดีโปรถบัส และบริษัทแท็กซี่"),
    ("Real unit economics", "เศรษฐศาสตร์ต่อหน่วยที่จับต้องได้"),
    ("S$70k-400k resale margin per BYD bus/truck and Wuling/Linxys van; S$10-15k per e-taxi.",
     "มาร์จิ้นขายต่อ 70,000-400,000 ดอลลาร์สิงคโปร์ต่อรถบัส/รถบรรทุก BYD และรถตู้ Wuling/Linxys; 10,000-15,000 ต่อแท็กซี่ไฟฟ้า"),
    ("09 · Series A structure", "09 · โครงสร้างซีรีส์ A"),
    ("Convertible bonds, by design", "หุ้นกู้แปลงสภาพ ออกแบบมาโดยตั้งใจ"),
    ("Investment protection", "การคุ้มครองเงินลงทุน"),
    ("Bond structure ranks ahead of equity, so capital is protected while the business scales.",
     "โครงสร้างหุ้นกู้มีลำดับสิทธิ์เหนือหุ้นสามัญ เงินทุนได้รับความคุ้มครองระหว่างธุรกิจขยายตัว"),
    ("Conversion incentives", "แรงจูงใจการแปลงสภาพ"),
    ("Convert into equity at preferential terms as milestones are hit: upside without re-negotiation.",
     "แปลงเป็นหุ้นในเงื่อนไขพิเศษเมื่อถึงเป้าหมาย: ได้อัปไซด์โดยไม่ต้องเจรจาใหม่"),
    ("Yield potential", "ศักยภาพผลตอบแทน"),
    ("Coupon income from day one, with equity upside preserved.", "รับดอกเบี้ยตั้งแต่วันแรก พร้อมคงอัปไซด์จากหุ้น"),
    ("The structure in one line", "สรุปในหนึ่งบรรทัด"),
    ("Secured assets against an upscaling revenue stream", "สินทรัพย์มีหลักประกัน รองรับกระแสรายได้ที่ขยายตัว"),
    ("10 · Use of funds", "10 · การใช้เงินทุน"),
    ("S$9.9M, deployed for scale", "9.9 ล้านดอลลาร์สิงคโปร์ เพื่อการขยายขนาด"),
    ("Vehicle inventory: pre-order buses &amp; taxis at bulk discount", "สต็อกยานพาหนะ: สั่งจองรถบัสและแท็กซี่ล่วงหน้าในราคาส่วนลด"),
    ("Three solar charging hubs: east, north, west", "ฮับชาร์จโซลาร์สามแห่ง: ตะวันออก เหนือ ตะวันตก"),
    ("Spare parts warehousing &amp; logistics", "คลังอะไหล่และโลจิสติกส์"),
    ("AI fleet platform: charging bookings, parts ordering", "แพลตฟอร์มฟลีต AI: จองชาร์จ สั่งอะไหล่"),
    ("Team &amp; sales: fleet sales, operations, engineering", "ทีมงานและฝ่ายขาย: ขายฟลีต ปฏิบัติการ วิศวกรรม"),
    ("11 · Roadmap", "11 · แผนงาน"),
    ("Scaling to 50,000 vehicles", "สู่เป้าหมาย 50,000 คัน"),
    ("Series A &amp; hubs", "ซีรีส์ A และฮับ"),
    ("Close the round, secure vehicle inventory, energise the first solar charging hubs.",
     "ปิดรอบระดมทุน ล็อกสต็อกยานพาหนะ เปิดใช้ฮับชาร์จโซลาร์ชุดแรก"),
    ("Scale inventory", "ขยายสต็อก"),
    ("Expand parts warehousing and vehicle stock; deepen operator subscriptions.",
     "ขยายคลังอะไหล่และสต็อกยานพาหนะ เพิ่มการสมัครสมาชิกของผู้ประกอบการ"),
    ("50,000+ vehicles", "50,000+ คัน"),
    ("Regional scale across Southeast Asia, with the flywheel compounding across markets.",
     "ขยายทั่วเอเชียตะวันออกเฉียงใต้ ฟลายวีลทบต้นข้ามตลาด"),
    ("Exit paths", "เส้นทาง Exit"),
    ("Acquisition by a regional energy / mobility player · IPO on SGX Catalist or Nasdaq",
     "ถูกซื้อกิจการโดยผู้เล่นพลังงานหรือโมบิลิตี้ระดับภูมิภาค · IPO บน SGX Catalist หรือ Nasdaq"),
    ("Join the quiet revolution.", "ร่วมปฏิวัติอันเงียบงัน"),
]

FIL = [
    ("Powering green.<br>Every kilometre, electrified.", "Berdeng enerhiya.<br>Bawat kilometro, de-kuryente."),
    ("Southeast Asia's integrated commercial EV ecosystem: vehicles, spare parts, and solar-powered charging under one roof.",
     "Ang pinagsamang commercial EV ecosystem ng Southeast Asia: mga sasakyan, spare parts, at solar na charging sa iisang bubong."),
    ("Series A · Confidential", "Series A · Kompidensyal"),
    ("01 · Who we are", "01 · Kung sino kami"),
    ("Twelve years in commercial transport.<br>Now fully electric.", "Labindalawang taon sa commercial transport.<br>Ngayon, ganap nang de-kuryente."),
    ("Transcool founded", "Itinatag ang Transcool"),
    ("Specialists in commercial air-conditioning systems for large vehicles, serving Singapore's biggest operators.",
     "Espesyalista sa commercial na air-conditioning para sa malalaking sasakyan, naglilingkod sa pinakamalalaking operator ng Singapore."),
    ("The electric pivot", "Ang pihit sa elektriko"),
    ("Evolved into integrated EV solutions as fleet electrification demand accelerated across the region.",
     "Naging integrated EV solutions habang bumibilis ang demand ng fleet electrification sa rehiyon."),
    ("A dedicated integrated EV reseller and provider: vehicles, parts, and charging as one ecosystem.",
     "Isang dedikadong integrated EV reseller at provider: sasakyan, parts, at charging bilang iisang ecosystem."),
    ("Long-standing corporate clients including SMRT and ComfortDelGro", "Matagalang corporate clients kabilang ang SMRT at ComfortDelGro"),
    ("Operations extended into Thailand and Malaysia", "Umabot na ang operasyon sa Thailand at Malaysia"),
    ("First integrated EV solution pilot deployed in Thailand", "Naipakat sa Thailand ang unang integrated EV solution pilot"),
    ("02 · The market", "02 · Ang merkado"),
    ("The commercial EV tipping point", "Ang tipping point ng commercial EV"),
    ("Global commercial EV market by 2026, entering hyper-growth", "Global na commercial EV market pagsapit ng 2026, papasok sa hyper-growth"),
    ("Light commercial EV demand: 1.14M units today to 16M+ by 2035",
     "Demand ng light commercial EV: 1.14M units ngayon tungo sa 16M+ pagsapit ng 2035"),
    ("Our focus: Southeast Asia, where OEM production meets infrastructure buildout",
     "Ang focus namin: Southeast Asia, kung saan nagtatagpo ang OEM production at infrastructure buildout"),
    ("03 · The problem", "03 · Ang problema"),
    ("Standard EVs fail modern fleets", "Bigo ang standard EVs sa modernong fleets"),
    ("Cost and supply barriers", "Hadlang sa gastos at supply"),
    ("Operators need large electric buses and taxis but face high upfront costs and unreliable supply chains.",
     "Kailangan ng mga operator ng malalaking electric bus at taxi pero hadlang ang mataas na paunang gastos at pabago-bagong supply chain."),
    ("Fragmented spare parts", "Watak-watak na spare parts"),
    ("Critical EV components take weeks to arrive, and every idle day is lost revenue for an operator.",
     "Inaabot ng ilang linggo ang kritikal na EV components, at bawat araw na nakatigil ay nawawalang kita."),
    ("Charging infrastructure gaps", "Kulang na charging infrastructure"),
    ("Grid strain, slow deployment, and high operating costs make depot charging painful to run.",
     "Grid strain, mabagal na deployment, at mataas na operating cost ang nagpapahirap sa depot charging."),
    ("Policy urgency, messy execution", "Apurahang polisiya, magulong execution"),
    ("Singapore's 2040 EV vision and 2030 bus electrification targets, with regional mandates following, create demand faster than operators can execute.",
     "Ang 2040 EV vision at 2030 bus electrification targets ng Singapore, kasunod ang mga mandato sa rehiyon, ay lumilikha ng demand nang mas mabilis kaysa kayang i-execute ng mga operator."),
    ("04 · Our solution", "04 · Ang solusyon namin"),
    ("One<br>ecosystem", "Iisang<br>ecosystem"),
    ('<span style="color: var(--accent-alt); font-size: 26px;">/ commercial EV sales</span>',
     '<span style="color: var(--accent-alt); font-size: 26px;">/ benta ng commercial EV</span>'),
    ("Large electric buses and e-taxis through proven OEM partnerships, an asset-light reseller model.",
     "Malalaking electric bus at e-taxi sa pamamagitan ng subok na OEM partnerships, isang asset-light na reseller model."),
    ('<span style="color: var(--accent-alt); font-size: 26px;">/ solar charging hubs</span>',
     '<span style="color: var(--accent-alt); font-size: 26px;">/ solar na charging hubs</span>'),
    ("On-site solar generation, battery storage, and fast DC charging built for fleet schedules.",
     "On-site solar generation, battery storage, at mabilis na DC charging na akma sa iskedyul ng fleet."),
    ('<span style="color: var(--accent-alt); font-size: 26px;">/ spare parts wholesale</span>',
     '<span style="color: var(--accent-alt); font-size: 26px;">/ pakyawang spare parts</span>'),
    ("Regional inventory hub for batteries, motors, AC/DC components, tyres, and brake parts.",
     "Panrehiyong inventory hub para sa baterya, motor, AC/DC components, gulong, at brake parts."),
    ("Vehicles → parts → renewable charging. Each arm feeds the next.",
     "Sasakyan → parts → renewable charging. Nagpapalakas ang bawat isa."),
    ("05 · Market opportunity", "05 · Oportunidad sa merkado"),
    ("A S$680M beachhead, a regional runway", "S$680M na beachhead, panrehiyong runway"),
    ("Singapore buses mandated 100% electric by 2040; only 240 electric today",
     "Mga bus ng Singapore na dapat 100% electric pagsapit ng 2040; 240 pa lang ang electric ngayon"),
    ("Singapore taxis electrifying: 2,500 electric today across Strides, ComfortDelGro, SMRT",
     "Nag-e-electrify ang mga taxi ng Singapore: 2,500 electric na sa Strides, ComfortDelGro, SMRT"),
    ("Five-year addressable market: vehicles, parts, and charging", "Limang-taong addressable market: sasakyan, parts, at charging"),
    ("Projected EV component and commercial vehicle market by 2035", "Inaasahang EV component at commercial vehicle market pagsapit ng 2035"),
    ("Regional expansion runway", "Panrehiyong expansion runway"),
    ("Malaysia · Thailand · Indonesia · Philippines", "Malaysia · Thailand · Indonesia · Pilipinas"),
    ("06 · Business model", "06 · Modelo ng negosyo"),
    ("Four streams, one blended margin", "Apat na stream, iisang blended margin"),
    ("<th>Revenue stream</th>", "<th>Pinagkakakitaan</th>"),
    ("<th>Description</th>", "<th>Paglalarawan</th>"),
    ("<td>Vehicle resale</td>", "<td>Benta ng sasakyan</td>"),
    ("15-18% commission / markup on bus and e-taxi sales", "15-18% komisyon o markup sa benta ng bus at e-taxi"),
    ("<td>Parts wholesale</td>", "<td>Pakyawang parts</td>"),
    ("B2B bulk spare parts with high repeat order rates", "B2B bulk spare parts na mataas ang repeat orders"),
    ("Pay-per-use charging plus fleet subscriptions", "Pay-per-use na charging at fleet subscriptions"),
    ("<td>Solar energy sales</td>", "<td>Benta ng solar</td>"),
    ("Excess solar sold to grid, offsetting charging costs", "Sobrang solar na ibinebenta sa grid, pambawas sa gastos sa charging"),
    ("Blended gross margin target", "Target na blended gross margin"),
    ("07 · Recurring revenue", "07 · Paulit-ulit na kita"),
    ("Fleet operators pay a monthly subscription for access to our solar-storage charging hubs",
     "Nagbabayad ang fleet operators ng buwanang subscription para sa aming solar-storage charging hubs"),
    ("We charge S$0.25/kWh against a S$0.35 grid rate: the client saves, we keep the margin plus renewable energy certificates",
     "Naniningil kami ng S$0.25/kWh laban sa S$0.35 na grid rate: nakakatipid ang kliyente, sa amin ang margin at renewable energy certificates"),
    ("Solar and storage integration lowers charging cost by 35% versus grid-only",
     "Pinabababa ng solar at storage ang gastos sa charging ng 35% kumpara sa grid-only"),
    ("Hubs anchor loyalty: charging customers buy vehicles and parts from the same ecosystem",
     "Nag-aangkla ng loyalty ang hubs: ang charging customers ay bumibili rin ng sasakyan at parts sa iisang ecosystem"),
    ("Our rate per kWh", "Ang rate namin kada kWh"),
    ("Grid rate per kWh", "Grid rate kada kWh"),
    ("Charging cost vs grid-only", "Gastos sa charging vs grid-only"),
    ("08 · Why we win", "08 · Bakit kami mananalo"),
    ("Six layers of moat", "Anim na patong ng moat"),
    ("Licensed &amp; compliant", "Lisensyado at sumusunod"),
    ("Fully licensed under Singapore's strict EV import and charging regulations.",
     "Ganap na lisensyado sa ilalim ng mahigpit na EV import at charging regulations ng Singapore."),
    ("Solar + storage edge", "Bentahe ng solar + storage"),
    ("35% cheaper charging than grid-only competitors, with RE certificate upside.",
     "35% na mas murang charging kaysa grid-only na kakumpitensya, may dagdag pang RE certificates."),
    ("Deep parts inventory", "Malalim na parts inventory"),
    ("Inverters, charging interfaces, and EV sensors in stock for minimal downtime versus new entrants, plus lifetime service contracts.",
     "Nakahandang inverters, charging interfaces, at EV sensors para sa minimal na downtime, may lifetime service contracts pa."),
    ("First mover", "Unang gumalaw"),
    ("The first integrated hub ecosystem for commercial fleets in the region.",
     "Ang unang integrated hub ecosystem para sa commercial fleets sa rehiyon."),
    ("12-year relationships", "12 taong relasyon"),
    ("Established sales relationships with LTA, bus depots, and taxi companies.",
     "Matibay na ugnayan sa LTA, bus depots, at mga kompanya ng taxi."),
    ("Real unit economics", "Totoong unit economics"),
    ("S$70k-400k resale margin per BYD bus/truck and Wuling/Linxys van; S$10-15k per e-taxi.",
     "S$70k-400k na resale margin kada BYD bus/truck at Wuling/Linxys van; S$10-15k kada e-taxi."),
    ("09 · Series A structure", "09 · Istruktura ng Series A"),
    ("Convertible bonds, by design", "Convertible bonds, sadyang dinisenyo"),
    ("Investment protection", "Proteksyon ng puhunan"),
    ("Bond structure ranks ahead of equity, so capital is protected while the business scales.",
     "Nakauuna ang bond structure sa equity, kaya protektado ang kapital habang lumalaki ang negosyo."),
    ("Conversion incentives", "Insentibo sa conversion"),
    ("Convert into equity at preferential terms as milestones are hit: upside without re-negotiation.",
     "Nagiging equity sa preferential terms kapag naabot ang milestones: upside nang walang muling negosasyon."),
    ("Yield potential", "Potensyal na yield"),
    ("Coupon income from day one, with equity upside preserved.", "Kita mula sa kupon simula unang araw, habang buo pa rin ang equity upside."),
    ("The structure in one line", "Ang istruktura sa isang linya"),
    ("Secured assets against an upscaling revenue stream", "Secured assets laban sa lumalaking revenue stream"),
    ("10 · Use of funds", "10 · Gamit ng pondo"),
    ("S$9.9M, deployed for scale", "S$9.9M, nakalaan para sa paglaki"),
    ("Vehicle inventory: pre-order buses &amp; taxis at bulk discount", "Vehicle inventory: pre-order ng bus at taxi sa bulk discount"),
    ("Three solar charging hubs: east, north, west", "Tatlong solar charging hubs: silangan, hilaga, kanluran"),
    ("Spare parts warehousing &amp; logistics", "Warehousing at logistics ng spare parts"),
    ("AI fleet platform: charging bookings, parts ordering", "AI fleet platform: charging bookings, pag-order ng parts"),
    ("Team &amp; sales: fleet sales, operations, engineering", "Team at sales: fleet sales, operations, engineering"),
    ("11 · Roadmap", "11 · Roadmap"),
    ("Scaling to 50,000 vehicles", "Pag-scale sa 50,000 sasakyan"),
    ("Series A &amp; hubs", "Series A at hubs"),
    ("Close the round, secure vehicle inventory, energise the first solar charging hubs.",
     "Isara ang round, siguruhin ang vehicle inventory, paandarin ang unang solar charging hubs."),
    ("Scale inventory", "Palakihin ang inventory"),
    ("Expand parts warehousing and vehicle stock; deepen operator subscriptions.",
     "Palawakin ang parts warehousing at vehicle stock; palalimin ang operator subscriptions."),
    ("50,000+ vehicles", "50,000+ sasakyan"),
    ("Regional scale across Southeast Asia, with the flywheel compounding across markets.",
     "Panrehiyong scale sa buong Southeast Asia, tumitindi ang flywheel sa bawat merkado."),
    ("Exit paths", "Mga exit path"),
    ("Acquisition by a regional energy / mobility player · IPO on SGX Catalist or Nasdaq",
     "Acquisition ng panrehiyong energy / mobility player · IPO sa SGX Catalist o Nasdaq"),
    ("Join the quiet revolution.", "Sumali sa tahimik na rebolusyon."),
]

TABLES = {"en": [], "zh": ZH, "th": TH, "fil": FIL}


def build(lang):
    html = open(SRC, encoding="utf-8").read()
    for old, new in TABLES[lang]:
        if old not in html:
            sys.exit(f"[{lang}] source string not found (deck copy changed?): {old[:70]}")
        html = html.replace(old, new)
    html = html.replace('<html lang="en">', f'<html lang="{lang}">', 1)
    if EXTRA_CSS[lang]:
        html = html.replace("</style>", EXTRA_CSS[lang] + "\n</style>", 1)
    tmp = os.path.join(HERE, f"_deck-{lang}.html")
    out = os.path.join(HERE, f"pitch-deck-{lang}.pdf")
    open(tmp, "w", encoding="utf-8").write(html)
    subprocess.run(
        [CHROME, "--headless=new", "--disable-gpu", f"--print-to-pdf={out}",
         "--no-pdf-header-footer", "--virtual-time-budget=30000", f"file://{tmp}"],
        check=True, capture_output=True,
    )
    os.remove(tmp)
    print(f"  {os.path.basename(out)}  {os.path.getsize(out)//1024} KB")


if __name__ == "__main__":
    for lang in ("en", "zh", "th", "fil"):
        build(lang)
    # legacy path used by older links
    shutil.copyfile(os.path.join(HERE, "pitch-deck-en.pdf"), os.path.join(HERE, "pitch-deck.pdf"))
    print("  pitch-deck.pdf (copy of en)")
